const names = require('./names')
const sayHi = require('./utils')
const data = require('./alternative_export')
// console.log(names)
require('./mind_grenade')
// sayHi('ibrahim')
// sayHi(names.jhon)
// sayHi(names.peter)
// console.log(data)
// 53:47